-- Create tasks table
create table public.tasks (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  is_complete boolean default false,
  user_id uuid references auth.users not null
);

-- Set up Row Level Security (RLS)
alter table public.tasks enable row level security;

-- Create policy to allow users to only see their own tasks
create policy "Users can view their own tasks"
  on public.tasks
  for select
  using (auth.uid() = user_id);

-- Create policy to allow users to insert their own tasks
create policy "Users can insert their own tasks"
  on public.tasks
  for insert
  with check (auth.uid() = user_id);

-- Create policy to allow users to update their own tasks
create policy "Users can update their own tasks"
  on public.tasks
  for update
  using (auth.uid() = user_id);

-- Create policy to allow users to delete their own tasks
create policy "Users can delete their own tasks"
  on public.tasks
  for delete
  using (auth.uid() = user_id);
